language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
  - PLONE_VERSION=4.2 TEST_EGGS=Pillow
  - PLONE_VERSION=4.3
matrix:
  fast_finish: true
install:
  - sed -ie "s#4.3.x.cfg#$PLONE_VERSION.x.cfg#" buildout.cfg
  - python bootstrap.py
  - bin/buildout buildout:test-eggs=$TEST_EGGS annotate
  - bin/buildout buildout:test-eggs=$TEST_EGGS
script:
  - bin/test
notifications:
  irc: irc.freenode.org#simplesconsultoria
